server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailtestcjh@gmail.com
    password: xohvhfpztqxdzaqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Agora?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password:
  oauth2:
   google:
    client-id: 클라이언트ID
    client-secret: 클라이언트SECRET
    redirect-uri: 리디렉션URI
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo 
mybatis:
  type-aliases-package: com.example.demo.vo
custom:
  siteName: Agora
  siteMainUri: http://localhost:8081
  emailFrom: no-reply@localhost
  emailFromName: Agora